function [YAPS, param_list] = read_meas_prot__struct(varargin)
%READ_MEAS_PROT__STRUCT
%
% [YAPS, param_list] = read_meas_prot__struct(varargin)

% Copyright © 2006-2012 Jonathan R. Polimeni and
%   The General Hospital Corporation (Boston, MA) "MGH"
%
% Terms and conditions for use, reproduction, distribution and contribution
% are found in the 'FreeSurfer Software License Agreement' contained
% in the file 'LICENSE' found in the FreeSurfer distribution, and here:
%
% https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSoftwareLicense


% jonathan polimeni <jonp@nmr.mgh.harvard.edu>, 2007/nov/18
% $Id: read_meas_prot__struct.m,v 1.10 2014/02/17 21:54:22 jonp Exp $
%**************************************************************************%

  VERSION = '$Revision: 1.10 $';


  %==--------------------------------------------------------------------==%

  % removed 'iMaxNoOfRxChannels', which is not helpful and was renamed to
  % 'lMaximumNofRxReceiverChannels' in the VD platform

  param_list = {'file', 'ulVersion', 'ManufacturersModelName', 'InstitutionName', 'tSequenceFileName', 'tProtocolName', 'tPatientPosition', ...
                'flNominalB0', 'lFrequency', 'flReferenceAmplitude', 'flAmplitude', ...
                'lBaseResolution', 'lPhaseEncodingLines', ...
                'iNoOfFourierColumns', 'iNoOfFourierLines', 'iNoOfFourierPartitions', ...
		'uc2DInterpolation', ...
                'lAccelFactPE', 'lAccelFact3D', ...
                'lRefLinesPE', 'lRefLines3D', ...
                'ucPATMode', 'ucRefScanMode', ...
		'ulCaipirinhaMode', 'lReorderingShift3D', 'CaipirinhaShift', ...
		'ucAsymmetricEchoAllowed', 'ucAsymmetricEchoMode', 'flAsymmetry_DERIVED', ...
                'ucPhasePartialFourier', 'ucSlicePartialFourier', ...
                'alTR', 'alTI', 'alTE', 'alTS', ...
                'alDwellTime', 'flBandwidthPerPixelPhaseEncode', 'iEffectiveEpiEchoSpacing', ...
                'lEPIFactor', ...
                'adFlipAngleDegree', ...
                'lRepetitions', 'lAverages', 'lContrasts', ...
                'dPhaseResolution', 'dSliceResolution', 'lPartitions', ...
                'lNoOfPhaseCorrScans', ...
                'flReadoutOSFactor', 'dPhaseOversamplingForDialog', 'dSliceOversamplingForDialog', ...
                'tGradientCoil', 'tCoilID', ...
                'sCoilElementID_tElement', ...
                'alRegridRampupTime', 'alRegridRampdownTime', ...
                'alRegridFlattopTime', 'alRegridDelaySamplesTime', ...
                'aflRegridADCDuration', ...
                'alRegridMode', 'ucRegridMode', ...
                'dThickness', 'dPhaseFOV', 'dReadoutFOV', ...
                'sSliceArray.lSize', 'sSliceArray', 'sSliceArray_reordered', ...
                'ucMultiSliceMode', 'sSliceArray.ucMode', ...
                'sDiffusion.lDiffDirections', 'sDiffusion.alBValue',  ...
                'sWiPMemBlock.alFree', 'sWiPMemBlock.adFree'};

  YAPS = cell2struct(cell(length(param_list),1), regexprep(param_list, '\.', '_'), 1);

  return;


  %************************************************************************%
  %%% $Source: /space/padkeemao/1/users/jonp/cvsjrp/PROJECTS/IMAGE_RECON/mrir_toolbox/read_meas_prot__struct.m,v $
  %%% Local Variables:
  %%% mode: Matlab
  %%% fill-column: 76
  %%% comment-column: 0
  %%% End:
